config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root 'home#index'

  resources :users
  resources :products

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :user
  has_one :photo

  mount_uploader :image_url, ImageUploader

  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :price, presence: true
  validates :image_url, presence: true

  scope :price_is_over, where(:price => 'red')

end

app/models/user.rb
class User < ApplicationRecord

  has_many :products
  before_save { self.email = email.downcase }

  validates :username, presence: true, uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
    length: { maximum: 105 },
    format: { with: VALID_EMAIL_REGEX }

  validates :password, length: { minimum: 8, maximum: 30 }
#  VALID_PASSWORD_REGEX = /\A((?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,})\z/
#  validates :password, format: { with: VALID_PASSWORD_REGAX }
#  message: " must contain at least one number, one uppercase and one lowercase letter with a minimum length of 8 chars."
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = current_user
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :logged_in_user?, only: [:new, :create, :edit, :destroy]

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.create(product_params)
    if @product.save
      redirect_to product_path(@product.id)
    else
      render 'new'
    end
  end

  def edit
    find_product
  end

  def update
    @product = find_product
    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    find_product
    @user_id = @product.user.id
    @product.destroy
    flash[:notice] = 'Item was deleted!'
    redirect_to user_path(@user_id)
  end

  def index
    @products = Product.all
  end

  def show
    find_product
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :category, :price, :image_url)
    end

    def find_product
      @product = Product.find(params[:id])
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      login(user)
      redirect_to '/'
    else
      flash.now[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      login(@user)
      redirect_to '/'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logged_in_user?
    unless logged_in?
      flash[:danger] = 'Need to login to access this feature!'
      redirect_to '/login'
    end
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end

  def admin
    if current_user.admin?
    end
  end
end

app/views/home/index.html.erb
<h1> This is the homepage </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <h1 align='center';>Peters Market</h1>
    <div class='banner-widget'>
      <ul>
        <% @user = current_user %>
          <li><%= link_to 'Home', root_path  %></li>
          <li><%= link_to "Item List", products_path %></li>
        <% if logged_in? %>
          <li><%= link_to @user.username, user_path(@user.id) %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", new_user_path  %></li>
        <% end %>
      </ul>
    </div>
  </head>

  <body class='background_image'>
        <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div align="center">
  <%= form_for @product do |f| %>
    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_field :description %>
    </p>
    <p>
      <%= f.label :category %><br/>
      <%= f.text_field :category %>
    </p>
     <p>
      <%= f.label :price %><br/>
      <%= f.text_field :price %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1 align='center'> Edit </h1>
<div align="center">
  <%= form_for @product do |f| %>
    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_field :description %>
    </p>
    <p>
      <%= f.label :category %><br/>
      <%= f.text_field :category %>
    </p>
     <p>
      <%= f.label :price %><br/>
      <%= f.text_field :price %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="list5" >
  <% @products.each do |product| %>
    <ol>
      <li><strong><%= product.name %></strong>
      <p>
      <%= link_to product_path(product) do %>
        <%= image_tag product.image_url.thumb.url, :class => "style_image" %>
      <% end %>
      </p>
      <ol>
        <li><strong>Category:</strong> <%= product.category %></li>
        <li><strong>Description:</strong> <%= product.description %></li>
        <li>£<%= product.price %></li>
      </ol>
      </li>
    </ol>
  <% end %>
</div>

app/views/products/new.html.erb
<h1 align='center'> New Product </h1>
<div align="center">
  <%= form_for @product do |f| %>
    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_field :description %>
    </p>
    <p>
      <%= f.label :category %><br/>
      <%= f.select :category, ['Mens', 'Womens', 'Homeware', 'Furniture', 'Jewelry', 'Electronics' ] %>
    </p>
    <p>
      <%= f.label :price %><br/>
      <%= f.text_field :price %>
    </p>
    <p>
      <%= f.label :image_url %></br>
      <%= f.file_field :image_url %></li>
    </p>
    <p>
    <%= f.submit %>
    </p>
  <% end %>
</div>

<% if @product.errors.any? %>
  <h2>The following errors stopped the article from saving</h2>
  <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/products/show.html.erb
<div class="list5" >
    <ol>
      <li><strong><%= @product.name %></strong>
      <p>
        <%= image_tag @product.image_url.thumb.url, :class => "style_image" %>
      </p>
      <ol>
        <li><strong>Category:</strong> <%= @product.category %></li>
        <li><strong>Description:</strong> <%= @product.description %></li>
        <li>£<%= @product.price %></li>
      </ol>
      </li>
    </ol>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <h2>The following errors prevented you from signing up!</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<h1 align='center'> Sign up! </h1>
<div align="center">
  <%= form_for @user do |f| %>
    <p>
      <%= f.label :username %><br/>
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label :email %><br/>
      <%= f.email_field :email %>
    </p>
    <p>
      <%= f.label :password %><br/>
      <%= f.password_field :password %>
    </p>
     <p>
      <%= f.label :password_confirmation %><br/>
      <%= f.password_field :password_confirmation %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/users/show.html.erb
<h1 align='center'> Hi, <%= @user.username %>! </h1>

<div align='center'>
  <p> <%= link_to 'List new item', new_product_path %> </p>
  <% @user.products.each do |product| %>
    <ul style="list-style-type: none;" >
      <li><%= product.name %>
      <%= product.description %>
      <% if logged_in? && current_user == product.user %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= link_to 'Show', product_path(product) %>
        <%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
      <% end %>
      <small>,
        <%= time_ago_in_words(product.created_at) %> ago,
        last updated: <%= time_ago_in_words(product.updated_at) %> ago</small></li>
    </ul>
  <% end %>
</div>